# Generated by Django 5.2.3 on 2025-07-15 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_commentmodel_fb_alter_commentmodel_tw_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='facbook_user_name',
            new_name='facebook_user_name',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
    ]
